"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class pos_t(object):
    __slots__ = ["timestamp", "position", "signal_strength"]

    def __init__(self):
        self.timestamp = 0.0
        self.position = [ 0.0 for dim0 in range(2) ]
        self.signal_strength = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(pos_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">d", self.timestamp))
        buf.write(struct.pack('>2d', *self.position[:2]))
        buf.write(struct.pack(">d", self.signal_strength))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != pos_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return pos_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = pos_t()
        self.timestamp = struct.unpack(">d", buf.read(8))[0]
        self.position = struct.unpack('>2d', buf.read(16))
        self.signal_strength = struct.unpack(">d", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if pos_t in parents: return 0
        tmphash = (0xc6d400d1a58536b1) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if pos_t._packed_fingerprint is None:
            pos_t._packed_fingerprint = struct.pack(">Q", pos_t._get_hash_recursive([]))
        return pos_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

